#!/bin/sh
# river/autostart

spawn="riverctl spawn"

$spawn "${HOME}/.local/bin/dam-run" &
$spawn "wlr-randr --output DP-4 --preferred" &
$spawn "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 0.3" &

killall -q fcitx5 swaybg &
$spawn "fcitx5 -d" &
$spawn "swaybg -i $HOME/media/wallpaper/green.png -m fill" &

pgrep -f "wl-clip-persist --clipboard regular" || $spawn "wl-clip-persist --clipboard regular" &
pgrep fnott || $spawn "fnott" &
