#!/bin/sh
# river/bindings

map="riverctl map"
pointer="riverctl map-pointer"
mod="Mod1"

# item
$map normal $mod Return spawn foot
$map normal $mod d spawn "pkill -x wmenu || j4-dmenu-desktop --dmenu 'wmenu -i' --term foot"
$map normal $mod e spawn firefox
$map normal $mod r spawn thunar
$map normal $mod v spawn pavucontrol-qt
$map normal Control q spawn "fcitx5-remote -t"
$map normal ${mod}+Control Up spawn "wlr-randr --output DP-4 --preferred"
$map normal ${mod}+Control Down spawn "wlr-randr --output DP-4 --mode 1280x1024@239.770996Hz"

# actions
$map normal $mod c close
$map normal $mod q zoom
$map normal $mod w toggle-float
$map normal $mod f toggle-fullscreen
$map normal ${mod}+Shift r spawn ${HOME}/.config/river/init
$map normal ${mod}+Shift End exit

# mouse
$pointer normal $mod BTN_LEFT move-view
$pointer normal $mod BTN_RIGHT resize-view

# capture
$map normal None F12 spawn ${HOME}/.config/river/scripts/screenshot.sh
$map normal None Print spawn ${HOME}/.config/river/scripts/wf-record.sh

# focus
$map normal $mod Left focus-view left
$map normal $mod Right focus-view right
$map normal $mod Up focus-view up
$map normal $mod Down focus-view down
$map normal $mod Tab focus-view next

# swap
$map normal ${mod}+Shift Left swap left
$map normal ${mod}+Shift Right swap right
$map normal ${mod}+Shift Up swap up
$map normal ${mod}+Shift Down swap down

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    $map normal $mod $i set-focused-tags $tags
    $map normal Control $i toggle-focused-tags $tags
    $map normal ${mod}+Shift $i set-view-tags $tags
    $map normal Control+Shift $i toggle-view-tags $tags
done

# volume
$map -repeat normal Mod4 Up spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"
$map -repeat normal Mod4 Down spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
